from io import BytesIO
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import TestCase
from zipfile import ZipFile
import base64
import codecs
import hashlib
import json
import re
import wave
import zlib

from blake3 import blake3
from PyQt5.QtGui import QImage

from src.misc.generate_checksum_fixtures import (
    FIXED_TIMESTAMP, _native_path, corpus_id, fixture_files, generate, inventory, verify,
)


REFERENCE_FILE = Path(__file__).resolve().parents[2] / 'resources' / 'ChecksumFiles' / 'v2' / 'references.json'
REFERENCE_ALGORITHMS = {
    'CheckSum.sfv': 'crc32', 'CheckSum.md5': 'md5', 'CheckSum.sha256': 'sha256',
    'CheckSum.blake3': 'blake3', 'CheckSum.sha3': 'sha3_256',
}
SFV_HEADER = '; Generated by WIN-SFV32 v1.0\r\n; (Compatible: Total Commander 11.58)\r\n'


def _tc_records(content, algorithm):
    """Read the exact Windows profiles in these fixtures, not arbitrary manifests."""
    if not content.startswith(codecs.BOM_UTF8):
        raise ValueError('Expected the observed UTF-8 BOM.')
    text = content.decode('utf-8-sig')
    if re.search(r'(?<!\r)\n|\r(?!\n)', text) or not text.endswith('\r\n'):
        raise ValueError('Expected the observed CRLF line endings.')
    if algorithm == 'crc32':
        pattern = re.compile(r'(?P<path>.+) (?P<digest>[0-9A-Fa-f]{8})')
    else:
        width = 32 if algorithm == 'md5' else 64
        separator = '  ' if algorithm == 'blake3' else r' \*'
        pattern = re.compile(r'(?P<digest>[0-9A-Fa-f]{' + str(width) + '})' + separator + r'(?P<path>.+)')
    records = {}
    for line in text.split('\r\n'):
        if not line:
            continue
        match = pattern.fullmatch(line)
        if match is None:
            if algorithm == 'crc32' and line.startswith(';'):
                continue
            raise ValueError('Unexpected TC fixture record: ' + ascii(line))
        path = match['path'].replace('\\', '/')
        if path in records:
            raise ValueError('Duplicate TC fixture path: ' + ascii(path))
        records[path] = match['digest'].lower()
    return records


def _file_digests(path):
    hashers = {
        'md5': hashlib.md5(usedforsecurity=False),
        'sha256': hashlib.sha256(),
        'sha3_256': hashlib.sha3_256(),
        'blake3': blake3(),
    }
    checksum = 0
    with path.open('rb') as source:
        while chunk := source.read(4 * 1024 * 1024):
            checksum = zlib.crc32(chunk, checksum)
            for hasher in hashers.values():
                hasher.update(chunk)
    return {'crc32': format(checksum & 0xffffffff, '08x'),
            **{name: hasher.hexdigest() for name, hasher in hashers.items()}}


class ChecksumFixturesTest(TestCase):
    def test_inventory_is_stable_and_covers_boundaries(self):
        first = inventory()
        self.assertEqual(first, inventory())
        self.assertEqual(2, first['version'])
        self.assertEqual('65ee48bccd569a243e63259bc93a367d4febfda983d08190274dba1e2e3f15dd',
                 corpus_id())
        self.assertEqual(83, len(first['files']))
        self.assertEqual(29375536, sum(entry['size'] for entry in first['files']))
        entries = {entry['path']: entry for entry in first['files']}
        self.assertEqual(len(entries), len(first['files']))
        self.assertEqual(26, sum('/' not in path for path in entries))
        self.assertFalse(any(path.startswith('data/') for path in entries))
        self.assertEqual('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
                 entries['empty.dat']['sha256'])
        self.assertTrue(any(len(path) > 260 for path in entries))
        self.assertTrue(any(any(ord(character) > 0xffff for character in path) for path in entries))
        sizes = {entry['size'] for entry in entries.values()}
        for boundary in (64, 136, 1024, 2048, 4 * 1024 * 1024):
            self.assertTrue({boundary - 1, boundary, boundary + 1} <= sizes)
        self.assertIn(16 * 1024 * 1024 + 1, sizes)

    def test_independent_roots_have_identical_bytes(self):
        with TemporaryDirectory() as temporary:
            first = Path(temporary) / 'first'
            second = Path(temporary) / 'another-root'
            self.assertEqual(generate(first), generate(second))
            self.assertEqual(verify(first), verify(second))
            for entry in fixture_files():
                self.assertEqual(FIXED_TIMESTAMP, int((_native_path(first) / entry.path).stat().st_mtime))
            reference = first / 'TC.sha256'
            reference.write_bytes(b'root reference manifest\n')
            self.assertEqual(inventory(), verify(first))
            self.assertEqual(b'root reference manifest\n', reference.read_bytes())

    def test_existing_destination_is_untouched(self):
        with TemporaryDirectory() as temporary:
            sentinel = Path(temporary) / 'keep.txt'
            sentinel.write_bytes(b'preserve this')
            with self.assertRaisesRegex(ValueError, 'must be empty'):
                generate(temporary)
            self.assertEqual(b'preserve this', sentinel.read_bytes())
            self.assertEqual([sentinel], list(Path(temporary).iterdir()))

    def test_tampered_bytes_are_rejected(self):
        with TemporaryDirectory() as temporary:
            generate(temporary)
            target = Path(temporary) / 'binary' / 'one-nul.bin'
            target.write_bytes(b'\x01')
            with self.assertRaisesRegex(ValueError, 'bytes differ'):
                verify(temporary)

    def test_extra_file_is_rejected(self):
        with TemporaryDirectory() as temporary:
            generate(temporary)
            (Path(temporary) / 'unexpected.txt').write_bytes(b'extra')
            with self.assertRaisesRegex(ValueError, 'file list differs'):
                verify(temporary)

    def test_nested_checksum_file_is_not_ignored(self):
        with TemporaryDirectory() as temporary:
            generate(temporary)
            (Path(temporary) / 'text' / 'unexpected.sha256').write_bytes(b'extra')
            with self.assertRaisesRegex(ValueError, 'file list differs'):
                verify(temporary)

    def test_archive_bytes_and_metadata_are_fixed(self):
        archive_entry = next(entry for entry in fixture_files() if entry.path.endswith('/stored.zip'))
        with ZipFile(BytesIO(archive_entry.pattern)) as archive:
            self.assertEqual(b'Unicode archive entry\n', archive.read('nested/caf\u00e9.txt'))
            self.assertIsNone(archive.testzip())
            for member in archive.infolist():
                self.assertEqual((2000, 1, 1, 0, 0, 0), member.date_time)
                self.assertEqual(0, member.compress_type)

    def test_media_formats_can_be_read(self):
        files = fixture_files()
        png = next(entry.pattern for entry in files if entry.path.endswith('/one-pixel.png'))
        image = QImage.fromData(png, 'PNG')
        self.assertFalse(image.isNull())
        self.assertEqual((1, 1), (image.width(), image.height()))
        audio = next(entry.pattern for entry in files if entry.path.endswith('/sample.wav'))
        with wave.open(BytesIO(audio), 'rb') as source:
            self.assertEqual((1, 1, 8000, 1024), (
                source.getnchannels(), source.getsampwidth(),
                source.getframerate(), source.getnframes(),
            ))


class TotalCommanderReferencesTest(TestCase):
    @classmethod
    def setUpClass(cls):
        cls.metadata = json.loads(REFERENCE_FILE.read_text(encoding='utf-8'))
        cls.payloads = {
            entry['filename']: base64.b64decode(entry['content_base64'], validate=True)
            for entry in cls.metadata['manifests']
        }
        if set(cls.payloads) != set(REFERENCE_ALGORITHMS):
            raise AssertionError('Unexpected TC reference set.')
        cls.temporary = TemporaryDirectory()
        cls.addClassCleanup(cls.temporary.cleanup)
        cls.root = Path(cls.temporary.name) / 'regenerated-corpus'
        generate(cls.root)
        for filename, content in cls.payloads.items():
            (cls.root / filename).write_bytes(content)
        cls.records = {
            filename: _tc_records(content, REFERENCE_ALGORITHMS[filename])
            for filename, content in cls.payloads.items()
        }
        expected_paths = {entry.path for entry in fixture_files()}
        if any(set(records) != expected_paths for records in cls.records.values()):
            raise AssertionError('TC references do not cover the exact corpus.')
        cls.actual = {
            entry.path: _file_digests(_native_path(cls.root) / entry.path)
            for entry in fixture_files()
        }

    def test_reference_integrity_and_corpus_version(self):
        self.assertEqual(2, self.metadata['corpus_version'])
        self.assertEqual(corpus_id(), self.metadata['corpus_sha256'])
        self.assertEqual(83, self.metadata['record_count'])
        self.assertEqual('utf-8-sig', self.metadata['observed_encoding'])
        self.assertEqual('CRLF', self.metadata['observed_line_endings'])
        for entry in self.metadata['manifests']:
            with self.subTest(filename=entry['filename']):
                content = self.payloads[entry['filename']]
                self.assertEqual(REFERENCE_ALGORITHMS[entry['filename']], entry['algorithm'])
                self.assertEqual(entry['byte_count'], len(content))
                self.assertEqual(entry['sha256'], hashlib.sha256(content).hexdigest())
                self.assertEqual(content, (self.root / entry['filename']).read_bytes())
                self.assertEqual(83, len(self.records[entry['filename']]))

    def test_all_tc_digests_match_regenerated_files(self):
        comparisons = 0
        for filename, records in self.records.items():
            algorithm = REFERENCE_ALGORITHMS[filename]
            for path, expected in records.items():
                with self.subTest(filename=filename, path=path):
                    self.assertEqual(expected, self.actual[path][algorithm])
                comparisons += 1
        self.assertEqual(415, comparisons)

    def test_reference_profiles_round_trip_exactly(self):
        for filename, records in self.records.items():
            algorithm = REFERENCE_ALGORITHMS[filename]
            lines = []
            for path in records:
                windows_path = path.replace('/', '\\')
                digest = self.actual[path][algorithm]
                if algorithm == 'crc32':
                    lines.append(windows_path + ' ' + digest.upper())
                else:
                    separator = '  ' if algorithm == 'blake3' else ' *'
                    lines.append(digest + separator + windows_path)
            header = SFV_HEADER if algorithm == 'crc32' else ''
            rebuilt = (header + '\r\n'.join(lines) + '\r\n').encode('utf-8-sig')
            with self.subTest(filename=filename):
                self.assertEqual(self.payloads[filename], rebuilt)

    def test_whitespace_unicode_and_long_paths_are_preserved(self):
        required = {' leading space.txt', ';semicolon.txt', 'names/;semicolon.txt',
                    'caf\u00e9.txt', 'cafe\u0301.txt', 'music-\U0001d11e.txt',
                    'percent%20 literal.txt', 'two  spaces.txt'}
        for filename, records in self.records.items():
            with self.subTest(filename=filename):
                self.assertTrue(required <= records.keys())
                self.assertEqual(26, sum('/' not in path for path in records))
                self.assertEqual(289, max(map(len, records)))
                self.assertEqual('00000000', self.records['CheckSum.sfv']['empty.dat'])

    def test_corrupt_file_disagrees_with_all_five_references(self):
        with TemporaryDirectory() as temporary:
            corrupt = Path(temporary) / 'one-nul.bin'
            corrupt.write_bytes(b'\x01')
            actual = _file_digests(corrupt)
            for filename, records in self.records.items():
                with self.subTest(filename=filename):
                    self.assertNotEqual(records['one-nul.bin'], actual[REFERENCE_ALGORITHMS[filename]])

    def test_missing_file_does_not_produce_a_digest(self):
        with TemporaryDirectory() as temporary:
            with self.assertRaises(FileNotFoundError):
                _file_digests(Path(temporary) / 'one-nul.bin')

    def test_json_checkout_line_endings_do_not_change_references(self):
        text = REFERENCE_FILE.read_text(encoding='utf-8')
        windows_checkout = json.loads(text.replace('\n', '\r\n'))
        for entry in windows_checkout['manifests']:
            self.assertEqual(self.payloads[entry['filename']],
                             base64.b64decode(entry['content_base64'], validate=True))